import { clamp } from '@robotics-lab/math'

export type Vector3State = {
	x: number
	y: number
	z: number
}

export type QuaternionState = {
	x: number
	y: number
	z: number
	w: number
}

export type DroneMissionState = 'idle' | 'armed' | 'flying' | 'landed'
export type MotorSpeeds = [
	frontLeft: number,
	frontRight: number,
	rearRight: number,
	rearLeft: number,
]
export type MotorId = 'front-left' | 'front-right' | 'rear-right' | 'rear-left'
export type RotorDirection = -1 | 1

export type DroneState = {
	position: Vector3State
	orientation: QuaternionState
	velocity: Vector3State
	angularVelocity: Vector3State
	batteryLevel: number
	missionState: DroneMissionState
	motorSpeeds: MotorSpeeds
}

export type QuadcopterParams = {
	mass: number
	armLength: number
	bodyRadius: number
	maxMotorSpeed: number
	thrustCoefficient: number
	torqueCoefficient: number
	hoverThrottle: number
}

export type MotorMount = {
	id: MotorId
	position: Vector3State
	spinDirection: RotorDirection
}

const GRAVITY = 9.81

const BASE_PARAMS = {
	mass: 1.2,
	armLength: 0.38,
	bodyRadius: 0.13,
	maxMotorSpeed: 900,
	thrustCoefficient: 0.000008,
	torqueCoefficient: 0.00000012,
}

/** Construct vehicle parameters and derive the normalized hover throttle. */
export function createQuadcopterParams(
	overrides: Partial<typeof BASE_PARAMS> = {},
): QuadcopterParams {
	const params = { ...BASE_PARAMS, ...overrides }
	const hoverMotorSpeed = Math.sqrt((params.mass * GRAVITY) / (4 * params.thrustCoefficient))
	return {
		...params,
		hoverThrottle: clamp(hoverMotorSpeed / params.maxMotorSpeed, 0, 1),
	}
}

export const DEFAULT_QUADCOPTER_PARAMS = createQuadcopterParams()

/** Create a complete, serializable drone state with an identity orientation. */
export function createDroneState(overrides: Partial<DroneState> = {}): DroneState {
	const state: DroneState = {
		position: { x: 0, y: 0, z: 0 },
		orientation: { x: 0, y: 0, z: 0, w: 1 },
		velocity: { x: 0, y: 0, z: 0 },
		angularVelocity: { x: 0, y: 0, z: 0 },
		batteryLevel: 100,
		missionState: 'landed',
		motorSpeeds: [0, 0, 0, 0],
		...overrides,
	}
	return { ...state, batteryLevel: clamp(state.batteryLevel, 0, 100) }
}

/** X-frame motor positions in body space, with the nose pointing toward +x. */
export function createRotorLayout(params: QuadcopterParams): readonly MotorMount[] {
	const offset = params.armLength / Math.sqrt(2)
	return [
		{ id: 'front-left', position: { x: offset, y: 0, z: -offset }, spinDirection: 1 },
		{ id: 'front-right', position: { x: offset, y: 0, z: offset }, spinDirection: -1 },
		{ id: 'rear-right', position: { x: -offset, y: 0, z: offset }, spinDirection: 1 },
		{ id: 'rear-left', position: { x: -offset, y: 0, z: -offset }, spinDirection: -1 },
	]
}

export function throttleToMotorSpeed(throttle: number, params: QuadcopterParams): number {
	return clamp(throttle, 0, 1) * params.maxMotorSpeed
}

/** Total body-space thrust. Rotating it into world space belongs to the physics milestone. */
export function calculateThrustVector(
	motorSpeeds: MotorSpeeds,
	params: QuadcopterParams,
): Vector3State {
	const upwardForce = motorSpeeds.reduce(
		(total, speed) => total + params.thrustCoefficient * speed * speed,
		0,
	)
	return { x: 0, y: upwardForce, z: 0 }
}

/** Body-space roll, yaw and pitch torque generated by the four rotors. */
export function calculateTorqueVector(
	motorSpeeds: MotorSpeeds,
	params: QuadcopterParams,
): Vector3State {
	const layout = createRotorLayout(params)
	return layout.reduce<Vector3State>(
		(torque, motor, index) => {
			const speed = motorSpeeds[index] ?? 0
			const thrust = params.thrustCoefficient * speed * speed
			const reactionTorque = motor.spinDirection * params.torqueCoefficient * speed * speed
			return {
				x: torque.x - motor.position.z * thrust,
				y: torque.y + reactionTorque,
				z: torque.z + motor.position.x * thrust,
			}
		},
		{ x: 0, y: 0, z: 0 },
	)
}

export * from './controls'
export * from './physics'
export * from './simulation'
